name: Build and Push to ECR

on:
  push:
    branches:
      - master  # Runs when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Build and tag Docker image
        run: |
          docker build -t week-4-repo .
          docker tag week-4-repo:latest public.ecr.aws/l1r3k7b9/week-4-repo:chamamme_nnyabe_to-do

      - name: Push image to Amazon ECR Public
        run: |
          docker push public.ecr.aws/l1r3k7b9/week-4-repo:chamamme_nnyabe_to-do
